export const FIELD_LIMITS = {
  TITLE_MAX: 200,
  DESCRIPTION_MAX: 20_000,
  COMMENT_BODY_MAX: 5_000,
  ATTACHMENTS_PER_ENTITY: 20,
  TAGS_PER_ENTITY: 15,
  BULK_ACTION_MAX: 200,
  SUBTASK_DEPTH_MAX: 5,
  FOLDER_DEPTH_MAX: 3,
  ENTITY_LINKS_MAX: 20,
  UNDO_HISTORY_SIZE: 50,
  TRASH_PURGE_DAYS: 30,
} as const
